
GET http://localhost:4000/health

###

POST http://localhost:4000/api/users/register HTTP/1.1
content-type: application/json

{
	"email": "daniel2@email.com",
	"password": "Zapata38",
  "name": "daniel",
	"age": 31,
	"role": "admin",
	"acceptTerms": true
}

###
POST http://localhost:4000/api/users/login HTTP/1.1
content-type: application/json

{
	"email": "daniel@email.com",
	"password": "Zapata38"
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYzUzMzVjYS0zNWMzLTRlZmItOWRiOS04N2RhNjI2MjI3MzAiLCJlbWFpbCI6ImRhbmllbEBlbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjEwNTMwODUsImV4cCI6MTc2MTY1Nzg4NX0.Sj3qocCXyAL0ulgk4o5uNoxlH9frxVNj1qG6dsWdx6w
GET http://localhost:4000/api/users?page=1&limit=10
Authorization: Bearer {{token}}
Accept: application/json


