
@id = ec5335ca-35c3-4efb-9db9-87da62622730
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjN2E0NjFjYy04MGU0LTRkZjQtODQ5My1lZWI5Njk2NWRiYTQiLCJlbWFpbCI6ImRhbmllbEBlbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjQwNjY5MDgsImV4cCI6MTc2NDE1MzMwOCwiYXVkIjoiZml0bmVzcy10cmFja2VyLXVzZXJzIiwiaXNzIjoiZml0bmVzcy10cmFja2VyLWFwcCJ9.Bq_U0Qt7DSFJ3DcPWKozpRi1n7P_D4C9UFqQTcAzU9Y
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNTU1M2VlMi01YWY5LTQ4NmQtOTA2Zi1lYTA2YjgxMjE0ZTQiLCJlbWFpbCI6ImFsZWphbmRybzdAZW1haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjQwNjY3NDQsImV4cCI6MTc2NDE1MzE0NCwiYXVkIjoiZml0bmVzcy10cmFja2VyLXVzZXJzIiwiaXNzIjoiZml0bmVzcy10cmFja2VyLWFwcCJ9.j_TsgxdSrh1IgoRBKSVLTwTGtXsBSwNEucyOUdrE-4I
@baseUrl = http://localhost:4000/api


# ==========================================
# PUBLIC ROUTES (No requieren autenticación)
# ==========================================


### Health Check
# check server status
GET http://localhost:4000/health

### POST /users/register
# registrar user

POST {{baseUrl}}/users/register HTTP/1.1
content-type: application/json

{
	"email": "alejandro7@email.com",
	"password": "Zapata38",
  "name": "alejandro",
	"age": 15,
	"acceptTerms": true
}

### POST /users/register
# registrar user admin

POST {{baseUrl}}/users/register HTTP/1.1
content-type: application/json

{
	"email": "daniel@email.com",
	"password": "Zapata38",
  "name": "daniel",
	"age": 31,
	"acceptTerms": true,
	"role": "admin"
}

### POST /users/login
# login user user

POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json

{
	"email": "alejandro7@email.com",
	"password": "Zapata38"
}

### POST /users/login
# login user admin
POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json

{
	"email": "daniel@email.com",
	"password": "Zapata38"
}

# ==========================================
#  PROTECTED ROUTES (Usuario autenticado)
# ==========================================

### GET /users/me
# get my profile
GET {{baseUrl}}/users/me HTTP/1.1
# Authorization: Bearer {{token}}
Authorization: Bearer {{userToken}}
Accept: application/json



### PATCH /users/me/password
# Cambiar contraseña del usuario autenticado
PATCH {{baseUrl}}/users/me/password HTTP/1.1
Authorization: Bearer {{userToken}}
content-type: application/json

{
	"oldPassword": "Zapata38",
	"newPassword": "Zapata39"
}



# // ============================================
# // ADMIN ROUTES
# // ============================================

# GET /users
### list users
GET {{baseUrl}}/users?page=1&limit=10 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

### DELETE /users/hardDelete:id
# hard delete user by id
DELETE {{baseUrl}}/users/hardDelete/394db242-5e3c-48db-8d0b-6762f0a3dce5 HTTP/1.1
Authorization: Bearer {{token}}
Accept: application/json

