@baseUrl = http://localhost:4000/api
@tokenUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJiNTU1M2VlMi01YWY5LTQ4NmQtOTA2Zi1lYTA2YjgxMjE0ZTQiLCJlbWFpbCI6ImFsZWphbmRybzdAZW1haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjQwNjcxMjMsImV4cCI6MTc2NDY3MTkyMywiYXVkIjoiZml0bmVzcy10cmFja2VyLXVzZXJzIiwiaXNzIjoiZml0bmVzcy10cmFja2VyLWFwcCJ9.fj0-PeXKyPMFiiVyuyjzmcEAzBHUXnmhyBLTYVLhmTY
@tokenAdmin =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjN2E0NjFjYy04MGU0LTRkZjQtODQ5My1lZWI5Njk2NWRiYTQiLCJlbWFpbCI6ImRhbmllbEBlbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjQwNjcxNTUsImV4cCI6MTc2NDY3MTk1NSwiYXVkIjoiZml0bmVzcy10cmFja2VyLXVzZXJzIiwiaXNzIjoiZml0bmVzcy10cmFja2VyLWFwcCJ9.lUH9Dpx-_qPdopKEMxmpbdyuHP04zm0yJm0ysa0VUU0
@workoutId = 4f6a8530-ec10-421d-b188-ff1bab04f807
### POST /users/login
# login user user
POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json

{
	"email": "alejandro7@email.com",
	"password": "Zapata39"
}

### POST /users/login
# login user admin
POST {{baseUrl}}/users/login HTTP/1.1
content-type: application/json

{
	"email": "daniel@email.com",
	"password": "Zapata38"
}

# // ============================================
# // WORKOUT ROUTES
# // ============================================

### POST /workouts
POST {{baseUrl}}/workouts HTTP/1.1
Authorization: Bearer {{tokenUser}}
content-type: application/json

{
	"title": "pecho",
	"notes": "Test Workout",
	"exercises": [
		{
			"exerciseId": "658805c3-58d9-4a85-befb-fe373d1495bd",
			"orderIndex": 0,
			"sets": [
				{
					"setNumber": 1,
					"reps": 10,
					"durationSeconds": 30,
					"restSeconds": 30,
					"weight": 100,
					"notes": "Test Set"
				},
				{
					"setNumber": 2,
					"reps": 10,
					"durationSeconds": 30,
					"restSeconds": 30,
					"weight": 100,
					"notes": "Test Set"
				}
			]
		},
		{
			"exerciseId": "456006d4-edb5-4c81-a065-c9fec1a77303",
			"orderIndex": 1,
			"sets": [
				{
					"setNumber": 1,
					"reps": 10,
					"restSeconds": 30,
					"notes": "Test Set"
				},
				{
					"setNumber": 2,
					"reps": 10,
					"restSeconds": 30,
					"notes": "Test Set"
				}
			]
		}
	]
}

### Listar workouts del usuario
GET {{baseUrl}}/workouts HTTP/1.1
Authorization: Bearer {{tokenUser}}
Accept: application/json

#### Con paginación
GET {{baseUrl}}/workouts?page=1&limit=10 HTTP/1.1
Authorization: Bearer {{tokenUser}}
Accept: application/json


### Con filtros de fecha
GET {{baseUrl}}/workouts?startDate=2025-01-01T00:00:00Z&endDate=2025-12-31T23:59:59Z HTTP/1.1
Authorization: Bearer {{tokenUser}}
Accept: application/json

### Con búsqueda
GET {{baseUrl}}/workouts?search=pecho HTTP/1.1
Authorization: Bearer {{tokenUser}}
Accept: application/json

### Get workout/:id
# get workout by id
GET {{baseUrl}}/workouts/{{workoutId}} HTTP/1.1
Authorization: Bearer {{tokenUser}}
Accept: application/json

### PATCH /workouts/:id
PATCH {{baseUrl}}/workouts/{{workoutId}} HTTP/1.1
Authorization: Bearer {{tokenUser}}
content-type: application/json

{
	"title": "pecho actualizado"
}	

### DELETE /workouts/:id
DELETE {{baseUrl}}/workouts/{{workoutId}} HTTP/1.1
Authorization: Bearer {{tokenUser}}

### GET /workouts/stats
GET {{baseUrl}}/workouts/stats HTTP/1.1
Authorization: Bearer {{tokenUser}}
Accept: application/json



